default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  password: <%= ENV.fetch("PG_PASSWORD") { ENV['tailwindsliu_DATABASE_PASSWORD'] } %>
  username: <%= ENV.fetch("PGUSER") { ENV["USER"] } %>

development:
  <<: *default
  database: tailwindsliu_development

test:
  <<: *default
  database: tailwindsliu_test

production:
  <<: *default
  database: tailwindsliu_production
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>